# Cloud Build configuration for Creseada RFQ Automation
# Builds and deploys both backend (FastAPI) and frontend (Next.js) to Cloud Run

substitutions:
  _REGION: us-central1
  _BACKEND_SERVICE: creseada-rfq-backend
  _FRONTEND_SERVICE: creseada-rfq-frontend
  # Set this to the Cloud SQL connection name output by Terraform
  # (format: <project>:<region>:<instance>)
  _CLOUDSQL_CONNECTION_NAME: ""
  # Set this to the Terraform-created bucket name
  _GCS_BUCKET: ""
  _GCS_PREFIX: rfq-poc
  # Shared token for Cloud Scheduler → /api/internal/sla/run
  _INTERNAL_CRON_TOKEN: ""

steps:
  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:latest'
      - '-f'
      - 'poc/Dockerfile'
      - '.'
    id: 'build-backend'

  # Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:latest'
      - '-f'
      - 'frontend/Dockerfile'
      - './frontend'
    id: 'build-frontend'
    waitFor: ['-']  # Run in parallel with backend build

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$COMMIT_SHA']
    id: 'push-backend'
    waitFor: ['build-backend']

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:$COMMIT_SHA']
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_BACKEND_SERVICE}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--add-cloudsql-instances'
      - '${_CLOUDSQL_CONNECTION_NAME}'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,GCP_REGION=${_REGION},GCS_BUCKET=${_GCS_BUCKET},GCS_PREFIX=${_GCS_PREFIX},INTERNAL_CRON_TOKEN=${_INTERNAL_CRON_TOKEN}'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Deploy frontend to Cloud Run (inject BACKEND_URL at deploy-time)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        BACKEND_URL="$(gcloud run services describe ${_BACKEND_SERVICE} --region ${_REGION} --format='value(status.url)')"
        echo "Deploying frontend with BACKEND_URL=${BACKEND_URL}"
        gcloud run deploy ${_FRONTEND_SERVICE} \
          --image gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:$COMMIT_SHA \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --memory 256Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 5 \
          --set-env-vars BACKEND_URL=${BACKEND_URL}
    id: 'deploy-frontend'
    waitFor: ['push-frontend', 'deploy-backend']

images:
  - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:latest'
  - 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:latest'

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
